./data/catalogue_latency_source_50.csv
51

50: []
Traceback (most recent call last):
  File "Microscope_online.py", line 689, in <module>
    rank = calc_sim(faults_name)
  File "Microscope_online.py", line 634, in calc_sim
    score.update({key: pearsonr(svc_latency_df[key].tolist()[-fklen:], locust_latency_50)[0]})
  File "/usr/python3/lib/python3.7/site-packages/scipy/stats/stats.py", line 3498, in pearsonr
    raise ValueError('x and y must have the same length.')
ValueError: x and y must have the same length.
